kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30080
        hostPort: 30080
  - role: worker
    extraMounts:
      - hostPath: /opt/self-hosting/kubernetes/baikal       # EDIT
        containerPath: /opt/self-hosting/kubernetes/baikal
